### ISSUE TITLE
Game codes don't parse correctly

### ISSUE THREAD

**Issue by Sanae6** [cybershard/wireshark-amongus#1]
A game with a code of `UOUZMS` (what I have at the moment) is parsed as `EYNLMY`.

**Comment by cybershard** [comment]
how does it feel to have the first official github issue (issue is fixed with commit https://github.com/cybershard/wireshark-amongus/commit/91d43702a3b43dbc8e087636b739df401168969b :smile: )

**Comment by Sanae6** [comment]
> 
> 
> how does it feel to have the first official github issue (issue is fixed with commit [91d4370](https://github.com/cybershard/wireshark-amongus/commit/91d43702a3b43dbc8e087636b739df401168969b) 😄 )

pretty good ngl
